version: '3.8'

services:
  web:
    build: .
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/code
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate && python manage.py collectstatic --no-input
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"